name: flutter_native_mutex
description: "A Flutter synchronization plugin which works across isolates"
version: 0.0.1
homepage: https://www.winkk.com/
repository: https://github.com/winkk-dev/flutter_native_mutex
issue_tracker: https://github.com/winkk-dev/flutter_native_mutex/issues

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.winkk.flutter_native_mutex
        pluginClass: FlutterNativeMutexPlugin
      ios:
        pluginClass: FlutterNativeMutexPlugin
